---
- hosts: all
  sudo: yes

  tasks:
    - name: Add Webmin repo
      apt_repository: >
       repo='{{ item }}'
       state=present
      with_items:
        - 'deb http://download.webmin.com/download/repository sarge contrib'
        - 'deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

    - name: Add Webmin key
      apt_key: >
       url='http://www.webmin.com/jcameron-key.asc'
       state=present

    - name: Install Webmin and prerequisites
      apt: >
       update_cache=yes
       pkg={{ item }}
       state=installed
      with_items:
        - perl
        - libnet-ssleay-perl
        - openssl
        - libauthen-pam-perl
        - libpam-runtime
        - libio-pty-perl
        - apt-show-versions
        - python
        - webmin

    - name: Update OS
      apt: update_cache=yes cache_valid_time=3600
      apt: upgrade=dist

    - name: Install software with apt
      apt: name={{ item }} state=present
      with_items:
        - vim
        - samba
        - samba-common-bin

    - name: Set HDD Spindown to 50 seconds
      command: hdparm -S 10 /dev/sda
