---
- hosts: all
  sudo: yes

  tasks:
    - name: Add Webmin repo
      apt_repository: >
       repo='{{ item }}'
       state=present
      with_items:
        - 'deb http://download.webmin.com/download/repository sarge contrib'
        - 'deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

    - name: Add Webmin key
      apt_key: >
       url='http://www.webmin.com/jcameron-key.asc'
       state=present

    - name: Install Webmin and prerequisites
      apt: >
       update_cache=yes
       pkg={{ item }}
       state=installed
      with_items:
        - perl
        - libnet-ssleay-perl
        - openssl
        - libauthen-pam-perl
        - libpam-runtime
        - libio-pty-perl
        - apt-show-versions
        - python
        - webmin

    - name: Update OS
      apt: update_cache=yes cache_valid_time=3600
      apt: upgrade=dist

    - name: Install software with apt
      apt: name={{ item }} state=present
      with_items:
        - vim
        - samba
        - samba-common-bin
        - libjna-java

    - name: Set HDD Spindown to 50 seconds
      command: hdparm -S 10 /dev/sda

    - name: Remove Crashplan jre
      command: rm -r /usr/local/crashplan/jre

    - name: Create symlink to pi JRE8 for Crashplan
      file:
        src: /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt
        dest: /usr/local/crashplan/jre
        state: link

    - name: Fix libjtux.so and libmd5.so for Crashplan
      get_url: url=http://www.jonrogers.co.uk/wp-content/uploads/2012/05/{{ item }} dest=/usr/local/crashplan
      with_items:
        - libjtux.so
        - libmd5.so
      
    - name: Edit CrashPlanEngine
      replace: >
       dest=/usr/local/crashplan/bin/CrashPlanEngine
       regexp='FULL_CP=\"\$TARGETDIR'
       replace='FULL_CP="/usr/share/java/jna.jar:$TARGETDIR'
       backup=yes
       
    - name: Run CrashPlan on startup
      command: update-rc.d crashplan defaults
